server:
  port: 8080
spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    # druid\u76F8\u5173\u914D\u7F6E
    druid:
      #\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters
      filter: stat
      # mysql\u9A71\u52A8
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.28.84.66:3306/seckill?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimeZone=GMT%2B8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      # \u95F4\u9694\u591A\u4E45\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5
      time-between-eviction-runs-millis: 60000

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

  #\u6587\u4EF6\u4E0A\u4F20\u76F8\u5173\u914D\u7F6E
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  #devtools\u63D2\u4EF6
  devtools:
    livereload:
      enabled: true #\u662F\u5426\u652F\u6301livereload
      port: 35729
    restart:
      enabled: true #\u662F\u5426\u652F\u6301\u70ED\u90E8\u7F72

  #Redis\u7F13\u5B58
  redis:
    #redis\u6570\u636E\u5E93\u7D22\u5F15\uFF0C\u9ED8\u8BA4\u4E3A0
    database: 0
    #\u670D\u52A1\u5668IP\u5730\u5740
    host: 172.28.84.66
    #\u5BC6\u7801\u9ED8\u8BA4\u4E3A\u7A7A
    password:
    #\u7AEF\u53E3\u53F7\u4E3A6379
    port: 6379
    #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4(\u6BEB\u79D2)
    timeout: 1000
    jedis:
      pool:
        # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-active: 8
        # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 8
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hyn.seckill.entity
  configuration:
    # \u4F7F\u7528JDBC\u7684getGeneratedKeys\uFF0C\u53EF\u4EE5\u83B7\u53D6\u6570\u636E\u5E93\u7684\u81EA\u589E\u4E3B\u952E\u503C
    use-generated-keys: true
    # \u4F7F\u7528\u5217\u522B\u540D\u66FF\u6362\u5217\u540D\uFF0C\u4F8B\u5982\uFF1Aselect name as title from table
    use-column-label: true
    # \u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u8F6C\u6362
    map-underscore-to-camel-case: true

# \u6253\u5370sql
logging:
  level:
    com.hyn.seckill.mapper: debug